version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/ma-retail-android

commands:
  build:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  test:
    steps:
      - run:
          name: Run Lint Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  fastlane_deploy:
    steps:
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Decode Android key store
          command: echo $KEYSTORE_BASE64 | base64 -di | tee keystore.jks app/keystore.jks >/dev/null
      - run:
          name: Store Google Service Account
          command: echo $PLAY_STORE_SERVICE_ACCOUNT_FILE > gcloud-service-account.json
      - run:
          name: "The number of the CircleCI build."
          command: echo ${CIRCLE_BUILD_NUM}
      - run:
          name: Deploy to (Google Play)
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              bundle exec fastlane deploy flavor:"dev"
            else
              bundle exec fastlane deploy flavor:"prod"
            fi
  The number of the CircleCI build

jobs:
  build_test:
    executor: android
    steps:
      - checkout
      - build
      - test
  deploy:
    executor: android
    steps:
      - checkout
      - fastlane_deploy

workflows:
  ma-retail-android_workflow:
    jobs:
      - build_test:
          context: BUILD
      - deploy:
          context: MOBILE_DEV
          requires:
            - build_test
          filters:
            branches:
              only: develop
      - deploy:
          context: MOBILE_PROD
          requires:
            - build_test
          filters:
            branches:
              only: master
