version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/ma-retail-android

commands:
  build:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  test:
    steps:
      - run:
          name: Run Lint Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build debug APK and release APK for Firebase Test Lab
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --app app/build/outputs/apk/debug/app-debug.apk \
              --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  fastlane_deploy:
    steps:
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Deploy to ${DEPLOY_TRACK} track (Google Play)
          command: bundle exec fastlane ${DEPLOY_TRACK}

jobs:
  build_test:
    executor: android
    steps:
      - checkout
      - build
      - test
  deploy:
    executor: android
    steps:
      - checkout
      - fastlane_deploy
workflows:
  ma-retail-android_workflow:
    jobs:
      - build_test:
          context: BUILD
      - deploy:
          context: MOBILE_DEV
          requires:
            - build_test
          filters:
            branches:
              only: develop
      - deploy:
          context: MOBILE_PROD
          requires:
            - build_test
          filters:
            branches:
              only: master