default_platform(:android)

platform :android do
  desc "Run the unit tests"
  lane :unit_tests do
    gradle(task: "test")
  end

  desc "Assemble a debug apk"
  lane :assemble_debug do
    gradle(task: "assembleDebug")
  end

  desc "Assemble an android test apk"
  lane :assemble_android_test do
    gradle(task: "assembleDebugAndroidTest")
  end

end