default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|

    gradle(
      task: "clean assemble",
      build_type: "Release",
      flavor: options[:flavor],
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
    file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    file_name = file_path.gsub(/\/.*\//, "")
    upload_to_play_store(
      track: ENV["PLAY_STORE_TRACK"],
      apk: file_path,
      json_key: "gcloud-service-account.json",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )

    notify_slack("New android app version deployed to the Google Play")
  end

  def notify_slack(message_text)
    slack(
      message: message_text,
      fail_on_error: false,
      slack_url: ENV["SLACK_URL"],
      default_payloads: [:git_branch, :git_author, :last_git_commit_hash],
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false,
    )
  end
end
