default_platform(:android)

platform :android do
  desc "Run beta deployment"
  lane :beta do
    gradle(task: "test")
  end

  desc "Run prod deployment"
  lane :prod do
    gradle(task: "assembleDebug")
  end

end